// Mocks generated by Mockito 5.3.0 from annotations
// in ditonton/test/features/watchlist/watchlist_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i10;

import 'package:ditonton/common/content_selection.dart' as _i5;
import 'package:ditonton/common/state_enum.dart' as _i7;
import 'package:ditonton/core/movie/domain/entities/movie.dart' as _i6;
import 'package:ditonton/core/movie/domain/usecase/get_watchlist_movies.dart'
    as _i2;
import 'package:ditonton/core/tv_series/domain/entities/tv_series.dart' as _i8;
import 'package:ditonton/core/tv_series/domain/usecase/get_watchlist_tv_series.dart'
    as _i3;
import 'package:ditonton/feature/watchlist/provider/watchlist_notifier.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetWatchlistMovies_0 extends _i1.SmartFake
    implements _i2.GetWatchlistMovies {
  _FakeGetWatchlistMovies_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGetWatchListTvSeries_1 extends _i1.SmartFake
    implements _i3.GetWatchListTvSeries {
  _FakeGetWatchListTvSeries_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [WatchlistNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistNotifier extends _i1.Mock implements _i4.WatchlistNotifier {
  MockWatchlistNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetWatchlistMovies get getWatchlistMovies =>
      (super.noSuchMethod(Invocation.getter(#getWatchlistMovies),
              returnValue: _FakeGetWatchlistMovies_0(
                  this, Invocation.getter(#getWatchlistMovies)))
          as _i2.GetWatchlistMovies);
  @override
  _i3.GetWatchListTvSeries get getWatchListTvSeries =>
      (super.noSuchMethod(Invocation.getter(#getWatchListTvSeries),
              returnValue: _FakeGetWatchListTvSeries_1(
                  this, Invocation.getter(#getWatchListTvSeries)))
          as _i3.GetWatchListTvSeries);
  @override
  _i5.ContentSelection get contentSelection =>
      (super.noSuchMethod(Invocation.getter(#contentSelection),
          returnValue: _i5.ContentSelection.movie) as _i5.ContentSelection);
  @override
  List<_i6.Movie> get watchlistMovies =>
      (super.noSuchMethod(Invocation.getter(#watchlistMovies),
          returnValue: <_i6.Movie>[]) as List<_i6.Movie>);
  @override
  _i7.RequestState get movieState =>
      (super.noSuchMethod(Invocation.getter(#movieState),
          returnValue: _i7.RequestState.Empty) as _i7.RequestState);
  @override
  List<_i8.TvSeries> get watchlistTvSeries =>
      (super.noSuchMethod(Invocation.getter(#watchlistTvSeries),
          returnValue: <_i8.TvSeries>[]) as List<_i8.TvSeries>);
  @override
  _i7.RequestState get tvSeriesState =>
      (super.noSuchMethod(Invocation.getter(#tvSeriesState),
          returnValue: _i7.RequestState.Empty) as _i7.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i9.Future<void> fetchWatchlistMovies() => (super.noSuchMethod(
      Invocation.method(#fetchWatchlistMovies, []),
      returnValue: _i9.Future<void>.value(),
      returnValueForMissingStub: _i9.Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> fetchWatchlistTvSeries() => (super.noSuchMethod(
      Invocation.method(#fetchWatchlistTvSeries, []),
      returnValue: _i9.Future<void>.value(),
      returnValueForMissingStub: _i9.Future<void>.value()) as _i9.Future<void>);
  @override
  void setSelectedContent(_i5.ContentSelection? content) =>
      super.noSuchMethod(Invocation.method(#setSelectedContent, [content]),
          returnValueForMissingStub: null);
  @override
  void addListener(_i10.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i10.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
