// Mocks generated by Mockito 5.3.2 from annotations
// in tv_series_detail/test/page/tv_series_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_bloc/flutter_bloc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_series_core/tv_series_core.dart' as _i2;
import 'package:tv_series_detail/src/cubit/tv_series_detail_cubit.dart' as _i3;
import 'package:tv_series_detail/src/cubit/tv_series_recommendations_cubit.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetDetailTvSeries_0 extends _i1.SmartFake
    implements _i2.GetDetailTvSeries {
  _FakeGetDetailTvSeries_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchlistStatus_1 extends _i1.SmartFake
    implements _i2.GetWatchlistStatus {
  _FakeGetWatchlistStatus_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveWatchlistTvSeries_2 extends _i1.SmartFake
    implements _i2.SaveWatchlistTvSeries {
  _FakeSaveWatchlistTvSeries_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveWatchlistTvSeries_3 extends _i1.SmartFake
    implements _i2.RemoveWatchlistTvSeries {
  _FakeRemoveWatchlistTvSeries_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesDetailState_4 extends _i1.SmartFake
    implements _i3.TvSeriesDetailState {
  _FakeTvSeriesDetailState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvSeriesRecommendations_5 extends _i1.SmartFake
    implements _i2.GetTvSeriesRecommendations {
  _FakeGetTvSeriesRecommendations_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesRecommendationsState_6 extends _i1.SmartFake
    implements _i4.TvSeriesRecommendationsState {
  _FakeTvSeriesRecommendationsState_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvSeriesDetailCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesDetailCubit extends _i1.Mock
    implements _i3.TvSeriesDetailCubit {
  MockTvSeriesDetailCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetDetailTvSeries get getDetailTvSeries => (super.noSuchMethod(
        Invocation.getter(#getDetailTvSeries),
        returnValue: _FakeGetDetailTvSeries_0(
          this,
          Invocation.getter(#getDetailTvSeries),
        ),
      ) as _i2.GetDetailTvSeries);
  @override
  _i2.GetWatchlistStatus get getWatchlistStatus => (super.noSuchMethod(
        Invocation.getter(#getWatchlistStatus),
        returnValue: _FakeGetWatchlistStatus_1(
          this,
          Invocation.getter(#getWatchlistStatus),
        ),
      ) as _i2.GetWatchlistStatus);
  @override
  _i2.SaveWatchlistTvSeries get saveWatchlistTvSeries => (super.noSuchMethod(
        Invocation.getter(#saveWatchlistTvSeries),
        returnValue: _FakeSaveWatchlistTvSeries_2(
          this,
          Invocation.getter(#saveWatchlistTvSeries),
        ),
      ) as _i2.SaveWatchlistTvSeries);
  @override
  _i2.RemoveWatchlistTvSeries get removeWatchlistTvSeries =>
      (super.noSuchMethod(
        Invocation.getter(#removeWatchlistTvSeries),
        returnValue: _FakeRemoveWatchlistTvSeries_3(
          this,
          Invocation.getter(#removeWatchlistTvSeries),
        ),
      ) as _i2.RemoveWatchlistTvSeries);
  @override
  _i3.TvSeriesDetailState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeTvSeriesDetailState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.TvSeriesDetailState);
  @override
  _i5.Stream<_i3.TvSeriesDetailState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.TvSeriesDetailState>.empty(),
      ) as _i5.Stream<_i3.TvSeriesDetailState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<void> fetchTvSeriesDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchTvSeriesDetail,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
        Invocation.method(
          #loadWatchlistStatus,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> addedToWatchlist(_i2.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
        Invocation.method(
          #addedToWatchlist,
          [tvSeries],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> removeFromWatchlist(_i2.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlist,
          [tvSeries],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  void emit(_i3.TvSeriesDetailState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i6.Change<_i3.TvSeriesDetailState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [TvSeriesRecommendationsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRecommendationsCubit extends _i1.Mock
    implements _i4.TvSeriesRecommendationsCubit {
  MockTvSeriesRecommendationsCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvSeriesRecommendations get getTvSeriesRecommendations =>
      (super.noSuchMethod(
        Invocation.getter(#getTvSeriesRecommendations),
        returnValue: _FakeGetTvSeriesRecommendations_5(
          this,
          Invocation.getter(#getTvSeriesRecommendations),
        ),
      ) as _i2.GetTvSeriesRecommendations);
  @override
  _i4.TvSeriesRecommendationsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeTvSeriesRecommendationsState_6(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.TvSeriesRecommendationsState);
  @override
  _i5.Stream<_i4.TvSeriesRecommendationsState> get stream =>
      (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i4.TvSeriesRecommendationsState>.empty(),
      ) as _i5.Stream<_i4.TvSeriesRecommendationsState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<void> fetchRecommendationsTvSeries(int? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchRecommendationsTvSeries,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  void emit(_i4.TvSeriesRecommendationsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i6.Change<_i4.TvSeriesRecommendationsState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
