name: Test and build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - submission2

permissions: read-all

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v2
        with:
          channel: master
        
      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get all packages and test
        run: make get && make test
  
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v2
        with:
          channel: master
      
      - name: Run flutter doctor
        run: flutter doctor -v
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Clean and get
        run: make clean && make get

      - name: Build APK
        run: flutter build apk